# Generated by Django 4.1.13 on 2024-10-28 17:35

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_and_answers', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('video_blob', models.BinaryField(null=True)),
                ('applicantid', models.CharField(default='0', max_length=100)),
                ('jobid', models.CharField(default='0', max_length=100)),
                ('stuttfeature_names', models.CharField(default='0', max_length=100)),
                ('postureresults', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('analysis_resultpersonality', djongo.models.fields.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('passw', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('dob', models.DateField(default=None)),
                ('exp', models.CharField(default='0', max_length=100)),
                ('post', models.CharField(choices=[('Intern', 'Intern'), ('Cleark', 'Cleark')], default='', max_length=13)),
                ('gen', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='', max_length=6)),
                ('applied', models.PositiveIntegerField(default=0)),
                ('ad1', models.CharField(default='', max_length=100)),
                ('ad2', models.CharField(default='', max_length=100)),
                ('pho1', models.CharField(default='0', max_length=100)),
                ('pho2', models.CharField(default='0', max_length=100)),
                ('work', models.CharField(choices=[('Open to Work', 'Open to Work'), ('Viewer', 'Viewer')], default='', max_length=13)),
                ('edu', models.CharField(default='', max_length=100)),
                ('per', models.CharField(default='', max_length=100)),
                ('uni', models.CharField(default='', max_length=100)),
                ('about', models.CharField(default='', max_length=1000)),
                ('interviewres', models.CharField(default='', max_length=1000)),
                ('applied_jobs', djongo.models.fields.JSONField(blank=True, default=list)),
                ('applied_interview', djongo.models.fields.JSONField(blank=True, default=list)),
                ('ranking', models.IntegerField(default=0)),
                ('skillstxt', models.TextField(default='')),
                ('skills', models.IntegerField(default=0)),
                ('match', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('interviewscore', models.IntegerField(default=0)),
                ('hrreview', models.TextField(default='')),
                ('resumetxt', models.TextField(default='')),
                ('resume', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
